### ISSUE TITLE
Using deprecated API

### ISSUE THREAD

**Issue by jonhue** [contextio/Ruby-ContextIO#41]
I am getting the following error when calling `cio.get_accounts`:

```
StandardError: HTTP code 401. Response {"value"=>"version 2.0 has been deprecated, please use lite"}
from C:/Dev/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/context_io-1.1.1/lib/context_io/utilities/call_helpers.rb:118:in `call_api'
```

Shouldn't this library use the lite API automatically?

**Comment by DaneCarmichael** [comment]
Hey Jonas,

Unfortunately this library was designed for the 2.0 API. It was decided that we were not going to update the it to use Lite.

Since you are expressing interest I will bring it up to our product manager to see if it is time to reevaluate this decision.

Thanks for reaching out to us!
